jobs:
  - job: 'Linux'
    strategy:
      matrix:
        clang_4:
          llvm_version: '6.0'
          CC: clang-$(llvm_version)
          CXX: clang++-$(llvm_version)
    pool:
      vmImage: ubuntu-16.04
    variables:
      CC: clang-$(llvm_version)
      CXX: clang++-$(llvm_version)
    timeoutInMinutes: 360
    steps:

      - script: |
          #LLVM_VERSION=$(llvm_version)
          #wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          #sudo add-apt-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-$LLVM_VERSION main"
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get --no-install-suggests --no-install-recommends install clang-$(llvm_version) 
        displayName: Install build toolchain

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - template: unix-build.yml
