jobs:
  - job: 'OSX'
    strategy:
      matrix:
        macOS_10_14:
          image_name: 'macOS-10.14'
    pool:
      vmImage: $(image_name)
    variables:
        CC: clang
        CXX: clang++
    timeoutInMinutes: 360
    steps:
      - script: |
          echo "Removing homebrew for Azure to avoid conflicts with conda"
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
          chmod +x ~/uninstall_homebrew
          ~/uninstall_homebrew -fq
        displayName: Remove homebrew

      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
          sudo chown -R $USER $CONDA
        displayName: Add conda to PATH

      - script: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda install cmake -c conda-forge
          conda install xtl==0.6.9 xsimd==7.4.4 nlohmann_json -c conda-forge
        displayName: Install dependencies

      - script: |
          mkdir build
          cd build
          cmake -DXTENSOR_USE_XSIMD=ON -DDOWNLOAD_GTEST=ON $(Build.SourcesDirectory)
        displayName: Configure xtensor
        workingDirectory: $(Build.BinariesDirectory)
      
      - script: |
          make -j2 test_xtensor_lib
        displayName: Build xtensor
        workingDirectory: $(Build.BinariesDirectory)/build
          
      - script: |
          cd test
          ./test_xtensor_lib
        displayName: Test xtensor
        workingDirectory: $(Build.BinariesDirectory)/build/test
